/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "erl_nif.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w;
typedef struct tyObject_Option__B2fjAwynjxmQWpd3bed9cLw tyObject_Option__B2fjAwynjxmQWpd3bed9cLw;
typedef struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA;
typedef struct tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ;
typedef struct tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
typedef N_NIMCALL_PTR(unsigned long long, tyProc__wReIQfculrbhygf8OIqnWw) (ErlNifEnv* env, int argc, unsigned long long* argv);
typedef NI32 tyEnum_ErlNifFlags__bBzsSUytLNIxpCBaOXqCag;
typedef ErlNifFunc tyArray__AyK9b5FdRVQxH3YlebcL8vg[3];
struct tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w {
NI32 val;
NIM_BOOL has;
};
struct tyObject_Option__B2fjAwynjxmQWpd3bed9cLw {
tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* val;
};
typedef unsigned long long tyArray__mkrXHkCDehl7KC6jLylMdg[2];
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g {
NimStringV2 val;
};
struct tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ {
NI a;
NI b;
};
typedef unsigned long long tyArray__mb9aqHXNNkFeLtIEP6aXMYQ[1];
struct TNimType {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
  Exception Sup;
};
struct tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct TNimNode {
char dummy;
};
struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA {
NF kp;
NF ki;
NF kf;
NF p;
NF i;
NF f;
NF r;
NF di;
NF min;
NF max;
NIM_BOOL integrate;
};
struct tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA {
NF val;
NIM_BOOL has;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, colonanonymous___dPeDdCnMoZuCgye5LFho4w)(ErlNifEnv* env, int argc, unsigned long long* argv);
static N_INLINE(NI32, get__eSiZpud1fqbLE55rzdD3SQoptions)(tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w self, NI32 otherwise);
static N_INLINE(NIM_BOOL, isSome__mick6IKW7paK9bdpVJrnJgQoptions)(tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w self);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w, from_term__zyO1yRfTECDMV9a6o3d00hQ)(ErlNifEnv* env, unsigned long long term);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, to_term__pJdsNsvteHR7m7nv0yKxZQ)(ErlNifEnv* env, NI32 V);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, create_resource__dPeDdCnMoZuCgye5LFho4w_2)(ErlNifEnv* env, int argc, unsigned long long* argv);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, new_resource__r9byBO1Ma6IFzl2uk8SWYUw)(ErlNifEnv* env);
static N_INLINE(NIM_BOOL, isNone__9c8EzI5kW85Knaeyi5R21aAoptions)(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw self);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, to_term__Ni0jSAiz9cWFkZ9aJeQUTbjg)(ErlNifEnv* env, tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g V);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___13i9ch7tdtUm3gbkon5nlrA)(unsigned long long* a, tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ x, unsigned long long* b, NI bLen_0);
static N_INLINE(tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ, dotdot___u9aQHCw3CKRH79cmJFUBLU9agsystem)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, to_term__9a9cLwpsgfxKoQ70eO0WYSNw)(ErlNifEnv* env, NimStringV2 V);
N_LIB_PRIVATE N_NIMCALL(void, init_controller__DrEjcoZ9bECTPpHDjBtiS3A)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* control, NF rate, NF min, NF max, NF kp, NF ki, NF kf);
static N_INLINE(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**, get__CynsSRaAL9c9a9clmpoVCgSqwoptions)(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw* self);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, release_resource__303jJuWZQeBLgwKlpOxU4Q)(ErlNifEnv* env, tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* V);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, update_resource__dPeDdCnMoZuCgye5LFho4w_3)(ErlNifEnv* env, int argc, unsigned long long* argv);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, get_resource__Wr1CzN6z01R3q9bCccSJpiA)(ErlNifEnv* env, unsigned long long term);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA, from_term__7J47caK3FAXHXyAsCwrmjA)(ErlNifEnv* env, unsigned long long term);
static N_INLINE(NIM_BOOL, isNone__9ceQCeoBXFptucCVWq2Pbswoptions)(tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA self);
N_LIB_PRIVATE N_NIMCALL(NF, update__hSL5GnyD0z5SnNrHLd50jA)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* control, NF sp, NF pv, NF f);
static N_INLINE(NF*, get__5nJrUvi9aIWOwCcVeE1Mszwoptions)(tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA* self);
N_LIB_PRIVATE N_NIMCALL(unsigned long long, to_term__GdqrB2DGxFMVhU2CgZ9c33A)(ErlNifEnv* env, NF V);
N_LIB_PRIVATE N_NIMCALL(int, on_load__8pPESl2pjVVSHE8sDlfHmQ)(ErlNifEnv* envX60gensym25510006_, void** priv_dataX60gensym25510007_, unsigned long long load_infoX60gensym25510008_);
N_LIB_PRIVATE N_NIMCALL(void, on_unload__zfoBJ1FmbMCz6PPaUkQHLw)(ErlNifEnv* envX60gensym25510012_, void* priv_dataX60gensym25510013_);
N_LIB_EXPORT N_CDECL(ErlNifEntry*, nif_init)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__XPEA3V09aI32RT0qKBrgPHQ_3 = { 5 | NIM_STRLIT_FLAG, "error" };
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_4 = {5, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_3};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__XPEA3V09aI32RT0qKBrgPHQ_5 = { 29 | NIM_STRLIT_FLAG, "fail to allocate new resource" };
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_6 = {29, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_5};
extern TNimType NTI__bq5YFIFutDsA2ou9cpZuWAQ_;
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__XPEA3V09aI32RT0qKBrgPHQ_7 = { 34 | NIM_STRLIT_FLAG, "Can\'t obtain a value from a `none`" };
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_8 = {34, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__XPEA3V09aI32RT0qKBrgPHQ_9 = { 2 | NIM_STRLIT_FLAG, "ok" };
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_10 = {2, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_9};
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_11 = {34, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_7};
static const NimStringV2 TM__XPEA3V09aI32RT0qKBrgPHQ_12 = {2, (NimStrPayload*)&TM__XPEA3V09aI32RT0qKBrgPHQ_9};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE tyArray__AyK9b5FdRVQxH3YlebcL8vg funcsX60gensym25520057___U9ahAE9cQZTjiKgTKDCPBxdQ;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
N_LIB_PRIVATE ErlNifEntry entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
static N_INLINE(NIM_BOOL, isSome__mick6IKW7paK9bdpVJrnJgQoptions)(tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w self) {
	NIM_BOOL result;
	nimfr_("isSome", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (NIM_BOOL)0;
	nimln_(144, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = self.has;
	popFrame();
	return result;
}
static N_INLINE(NI32, get__eSiZpud1fqbLE55rzdD3SQoptions)(tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w self, NI32 otherwise) {
	NI32 result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimln_(189, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	nimln_(198, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__mick6IKW7paK9bdpVJrnJgQoptions(self);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = self.val;
	}
	goto LA1_;
	LA4_: ;
	{
		result = otherwise;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long long, colonanonymous___dPeDdCnMoZuCgye5LFho4w)(ErlNifEnv* env, int argc, unsigned long long* argv) {
	unsigned long long result;
	NI32 a1;
	tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w T1_;
	NI32 a2;
	tyObject_Option__qXpOBk6YAm7MMF5pjbEt7w T2_;
	NI32 r;
	NI TM__XPEA3V09aI32RT0qKBrgPHQ_2;
NIM_BOOL* nimErr_;
	nimfr_(":anonymous", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
{nimErr_ = nimErrorFlag();
	result = (unsigned long long)0;
	nimln_(45, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T1_ = from_term__zyO1yRfTECDMV9a6o3d00hQ(env, argv[((NI) 0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	a1 = get__eSiZpud1fqbLE55rzdD3SQoptions(T1_, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(46, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T2_ = from_term__zyO1yRfTECDMV9a6o3d00hQ(env, argv[((NI) 1)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	a2 = get__eSiZpud1fqbLE55rzdD3SQoptions(T2_, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(47, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	if (nimAddInt(a1, a2, &TM__XPEA3V09aI32RT0qKBrgPHQ_2)) { raiseOverflow(); goto BeforeRet_;
};
	if (TM__XPEA3V09aI32RT0qKBrgPHQ_2 < (-2147483647 -1) || TM__XPEA3V09aI32RT0qKBrgPHQ_2 > 2147483647){ raiseOverflow(); goto BeforeRet_;
}
	r = (NI32)(TM__XPEA3V09aI32RT0qKBrgPHQ_2);
	nimln_(48, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	result = to_term__pJdsNsvteHR7m7nv0yKxZQ(env, r);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__9c8EzI5kW85Knaeyi5R21aAoptions)(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw self) {
	NIM_BOOL result;
	nimfr_("isNone", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (NIM_BOOL)0;
	nimln_(158, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	nimln_(166, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (self.val == 0);
	popFrame();
	return result;
}
static N_INLINE(tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ, dotdot___u9aQHCw3CKRH79cmJFUBLU9agsystem)(NI a, NI b) {
	tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ result;
	nimfr_("..", "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ));
	nimln_(474, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ));
	result.a = a;
	result.b = b;
	popFrame();
	return result;
}
static N_INLINE(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**, get__CynsSRaAL9c9a9clmpoVCgSqwoptions)(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw* self) {
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA** result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**)0;
	nimln_(184, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__9c8EzI5kW85Knaeyi5R21aAoptions((*self));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ*)0;
		T6_ = (tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ*) nimNewObj(sizeof(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI__bq5YFIFutDsA2ou9cpZuWAQ_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__XPEA3V09aI32RT0qKBrgPHQ_8;
		(*T6_).Sup.Sup.parent = NIM_NIL;
		nimln_(185, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim", 185);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(186, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = &(*self).val;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long long, create_resource__dPeDdCnMoZuCgye5LFho4w_2)(ErlNifEnv* env, int argc, unsigned long long* argv) {
	unsigned long long result;
	tyObject_Option__B2fjAwynjxmQWpd3bed9cLw res;
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA** T11_;
	tyArray__mkrXHkCDehl7KC6jLylMdg result_tupX60gensym25475001_;
	tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g T12_;
	unsigned long long T13_;
	tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ T14_;
	tyArray__mb9aqHXNNkFeLtIEP6aXMYQ T15_;
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA** T16_;
	unsigned long long T17_;
NIM_BOOL* nimErr_;
	nimfr_("create_resource", "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
{nimErr_ = nimErrorFlag();
	result = (unsigned long long)0;
	nimln_(19, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	res = new_resource__r9byBO1Ma6IFzl2uk8SWYUw(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(21, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	{
		NIM_BOOL T3_;
		tyArray__mkrXHkCDehl7KC6jLylMdg result_tupX60gensym25460001_;
		tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g T6_;
		unsigned long long T7_;
		tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ T8_;
		tyArray__mb9aqHXNNkFeLtIEP6aXMYQ T9_;
		unsigned long long T10_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__9c8EzI5kW85Knaeyi5R21aAoptions(res);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(22, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
		nimZeroMem((void*)result_tupX60gensym25460001_, sizeof(tyArray__mkrXHkCDehl7KC6jLylMdg));
		nimln_(224, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
		nimZeroMem((void*)(&T6_), sizeof(tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g));
		T6_.val = TM__XPEA3V09aI32RT0qKBrgPHQ_4;
		T7_ = (unsigned long long)0;
		T7_ = to_term__Ni0jSAiz9cWFkZ9aJeQUTbjg(env, T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result_tupX60gensym25460001_[(((NI) 0))- 0] = T7_;
		nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
		T8_ = dotdot___u9aQHCw3CKRH79cmJFUBLU9agsystem(((NI) 1), ((NI) 1));
		nimln_(22, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
		T10_ = (unsigned long long)0;
		T10_ = to_term__9a9cLwpsgfxKoQ70eO0WYSNw(env, TM__XPEA3V09aI32RT0qKBrgPHQ_6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T9_[0] = T10_;
		nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
		X5BX5Deq___13i9ch7tdtUm3gbkon5nlrA(result_tupX60gensym25460001_, T8_, T9_, 1);
		nimln_(22, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
		result = enif_make_tuple_from_array(env, result_tupX60gensym25460001_, 2);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(24, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T11_ = (tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**)0;
	T11_ = get__CynsSRaAL9c9a9clmpoVCgSqwoptions((&res));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	init_controller__DrEjcoZ9bECTPpHDjBtiS3A((*T11_), 1.0000000000000000e+02, -1.0000000000000000e+01, 1.0000000000000000e+01, 5.0000000000000000e-01, 2.5000000000000000e-01, 1.0000000000000000e+00);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(25, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	nimZeroMem((void*)result_tupX60gensym25475001_, sizeof(tyArray__mkrXHkCDehl7KC6jLylMdg));
	nimln_(222, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	nimZeroMem((void*)(&T12_), sizeof(tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g));
	T12_.val = TM__XPEA3V09aI32RT0qKBrgPHQ_10;
	T13_ = (unsigned long long)0;
	T13_ = to_term__Ni0jSAiz9cWFkZ9aJeQUTbjg(env, T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result_tupX60gensym25475001_[(((NI) 0))- 0] = T13_;
	nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	T14_ = dotdot___u9aQHCw3CKRH79cmJFUBLU9agsystem(((NI) 1), ((NI) 1));
	nimln_(25, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T16_ = (tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**)0;
	T16_ = get__CynsSRaAL9c9a9clmpoVCgSqwoptions((&res));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T17_ = (unsigned long long)0;
	T17_ = release_resource__303jJuWZQeBLgwKlpOxU4Q(env, (*T16_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T15_[0] = T17_;
	nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	X5BX5Deq___13i9ch7tdtUm3gbkon5nlrA(result_tupX60gensym25475001_, T14_, T15_, 1);
	nimln_(25, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	result = enif_make_tuple_from_array(env, result_tupX60gensym25475001_, 2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isNone__9ceQCeoBXFptucCVWq2Pbswoptions)(tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA self) {
	NIM_BOOL result;
	nimfr_("isNone", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (NIM_BOOL)0;
	nimln_(158, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	nimln_(168, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = !(self.has);
	popFrame();
	return result;
}
static N_INLINE(NF*, get__5nJrUvi9aIWOwCcVeE1Mszwoptions)(tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA* self) {
	NF* result;
NIM_BOOL* nimErr_;
	nimfr_("get", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (NF*)0;
	nimln_(184, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		NIM_BOOL T3_;
		tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__9ceQCeoBXFptucCVWq2Pbswoptions((*self));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = (tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ*)0;
		T6_ = (tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ*) nimNewObj(sizeof(tyObject_UnpackDefect__bq5YFIFutDsA2ou9cpZuWAQ));
		(*T6_).Sup.Sup.Sup.m_type = (&NTI__bq5YFIFutDsA2ou9cpZuWAQ_);
		(*T6_).Sup.Sup.name = "UnpackDefect";
		(*T6_).Sup.Sup.message = TM__XPEA3V09aI32RT0qKBrgPHQ_11;
		(*T6_).Sup.Sup.parent = NIM_NIL;
		nimln_(185, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
		raiseExceptionEx((Exception*)T6_, "UnpackDefect", "get", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim", 185);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(186, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (&(*self).val);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long long, update_resource__dPeDdCnMoZuCgye5LFho4w_3)(ErlNifEnv* env, int argc, unsigned long long* argv) {
	unsigned long long result;
	tyObject_Option__B2fjAwynjxmQWpd3bed9cLw resource;
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* controller;
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA** T6_;
	tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA sp;
	tyObject_Option__MBAh7IvpI0zpyfBz2BbYLA pv;
	NF res;
	NF* T13_;
	NF* T14_;
	tyArray__mkrXHkCDehl7KC6jLylMdg result_tupX60gensym25490001_;
	tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g T15_;
	unsigned long long T16_;
	tyObject_HSlice__i2Z64wI53ZCthDOLA9cD8mQ T17_;
	tyArray__mb9aqHXNNkFeLtIEP6aXMYQ T18_;
	unsigned long long T19_;
NIM_BOOL* nimErr_;
	nimfr_("update_resource", "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
{nimErr_ = nimErrorFlag();
	result = (unsigned long long)0;
	nimln_(28, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	resource = get_resource__Wr1CzN6z01R3q9bCccSJpiA(env, argv[((NI) 0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(30, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNone__9c8EzI5kW85Knaeyi5R21aAoptions(resource);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(31, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
		result = enif_make_badarg(env);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(33, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T6_ = (tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA**)0;
	T6_ = get__CynsSRaAL9c9a9clmpoVCgSqwoptions((&resource));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	controller = (*T6_);
	nimln_(34, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	sp = from_term__7J47caK3FAXHXyAsCwrmjA(env, argv[((NI) 1)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(35, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	pv = from_term__7J47caK3FAXHXyAsCwrmjA(env, argv[((NI) 2)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(37, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	{
		NIM_BOOL T9_;
		T9_ = (NIM_BOOL)0;
		T9_ = isNone__9ceQCeoBXFptucCVWq2Pbswoptions(sp);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (T9_) goto LA10_;
		T9_ = isNone__9ceQCeoBXFptucCVWq2Pbswoptions(pv);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		LA10_: ;
		if (!T9_) goto LA11_;
		nimln_(38, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
		result = enif_make_badarg(env);
		goto BeforeRet_;
	}
	LA11_: ;
	nimln_(40, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T13_ = (NF*)0;
	T13_ = get__5nJrUvi9aIWOwCcVeE1Mszwoptions((&sp));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T14_ = (NF*)0;
	T14_ = get__5nJrUvi9aIWOwCcVeE1Mszwoptions((&pv));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	res = update__hSL5GnyD0z5SnNrHLd50jA(controller, (*T13_), (*T14_), 0.0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(42, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	nimZeroMem((void*)result_tupX60gensym25490001_, sizeof(tyArray__mkrXHkCDehl7KC6jLylMdg));
	nimln_(222, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	nimZeroMem((void*)(&T15_), sizeof(tyObject_ErlAtom__a49atspohaYlyxys5xHmw1g));
	T15_.val = TM__XPEA3V09aI32RT0qKBrgPHQ_12;
	T16_ = (unsigned long long)0;
	T16_ = to_term__Ni0jSAiz9cWFkZ9aJeQUTbjg(env, T15_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result_tupX60gensym25490001_[(((NI) 0))- 0] = T16_;
	nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	T17_ = dotdot___u9aQHCw3CKRH79cmJFUBLU9agsystem(((NI) 1), ((NI) 1));
	nimln_(42, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	T19_ = (unsigned long long)0;
	T19_ = to_term__GdqrB2DGxFMVhU2CgZ9c33A(env, res);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T18_[0] = T19_;
	nimln_(219, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/codec.nim");
	X5BX5Deq___13i9ch7tdtUm3gbkon5nlrA(result_tupX60gensym25490001_, T17_, T18_, 1);
	nimln_(42, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	result = enif_make_tuple_from_array(env, result_tupX60gensym25490001_, 2);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, on_load__8pPESl2pjVVSHE8sDlfHmQ)(ErlNifEnv* envX60gensym25510006_, void** priv_dataX60gensym25510007_, unsigned long long load_infoX60gensym25510008_) {
	int result;
	int flagsX60gensym25510009_;
	int flags_triedX60gensym25510010_;
	ErlNifResourceType* open_resX60gensym25510011_;
	nimfr_("on_load", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
{	result = (int)0;
	nimln_(28, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	flagsX60gensym25510009_ = ((int) (3));
	flags_triedX60gensym25510010_ = (int)0;
	nimln_(30, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	open_resX60gensym25510011_ = enif_open_resource_type(envX60gensym25510006_, NIM_NIL, "Elixir.Controller", NIM_NIL, flagsX60gensym25510009_, (&flags_triedX60gensym25510010_));
	nimln_(31, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	{
		if (!(open_resX60gensym25510011_ == 0)) goto LA3_;
		result = ((int) -1);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(32, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	(*priv_dataX60gensym25510007_) = ((void*) (open_resX60gensym25510011_));
	nimln_(33, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	result = ((int) 0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, on_unload__zfoBJ1FmbMCz6PPaUkQHLw)(ErlNifEnv* envX60gensym25510012_, void* priv_dataX60gensym25510013_) {
	nimfr_("on_unload", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	nimln_(36, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	enif_free(priv_dataX60gensym25510013_);
	popFrame();
}
N_LIB_EXPORT N_CDECL(ErlNifEntry*, nif_init)(void) {
	ErlNifEntry* result;
	nimfr_("nif_init", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	result = (ErlNifEntry*)0;
	nimln_(79, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	NimMain();
	nimln_(80, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	result = (&entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA);
	popFrame();
	return result;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	stdlib_optionsDatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	ErlNifFunc T1_;
	ErlNifFunc T2_;
	ErlNifFunc T3_;
	nimfr_("libwidgetlords_nifs", "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	nimln_(64, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	nimZeroMem((void*)(&T1_), sizeof(ErlNifFunc));
	T1_.name = "add_numbers";
	T1_.arity = ((unsigned int) 2);
	T1_.fptr = colonanonymous___dPeDdCnMoZuCgye5LFho4w;
	T1_.flags = ((tyEnum_ErlNifFlags__bBzsSUytLNIxpCBaOXqCag) 0);
	funcsX60gensym25520057___U9ahAE9cQZTjiKgTKDCPBxdQ[0] = T1_;
	nimZeroMem((void*)(&T2_), sizeof(ErlNifFunc));
	T2_.name = "create_resource";
	T2_.arity = ((unsigned int) 0);
	T2_.fptr = create_resource__dPeDdCnMoZuCgye5LFho4w_2;
	T2_.flags = ((tyEnum_ErlNifFlags__bBzsSUytLNIxpCBaOXqCag) 2);
	funcsX60gensym25520057___U9ahAE9cQZTjiKgTKDCPBxdQ[1] = T2_;
	nimZeroMem((void*)(&T3_), sizeof(ErlNifFunc));
	T3_.name = "update_resource";
	T3_.arity = ((unsigned int) 3);
	T3_.fptr = update_resource__dPeDdCnMoZuCgye5LFho4w_3;
	T3_.flags = ((tyEnum_ErlNifFlags__bBzsSUytLNIxpCBaOXqCag) 0);
	funcsX60gensym25520057___U9ahAE9cQZTjiKgTKDCPBxdQ[2] = T3_;
	nimln_(51, "/home/elcritch/projects/pt/widgetlords_nifs/src/libwidgetlords_"
"nifs.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.name = "Elixir.Controller";
	nimln_(67, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.num_of_funcs = ((int) 3);
	nimln_(68, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	{
		if (!NIM_TRUE) goto LA6_;
		nimln_(69, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
		entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.funcs = (&funcsX60gensym25520057___U9ahAE9cQZTjiKgTKDCPBxdQ[(((NI) 0))- 0]);
	}
	LA6_: ;
	nimln_(70, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.major = ((int) 2);
	nimln_(71, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.minor = ((int) 15);
	nimln_(72, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.vm_variant = "beam.vanilla";
	nimln_(38, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.load = ((void*) (on_load__8pPESl2pjVVSHE8sDlfHmQ));
	nimln_(60, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.reload = ((void*) (NIM_NIL));
	nimln_(61, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.upgrade = ((void*) (NIM_NIL));
	nimln_(38, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	entryX60gensym25520058___9btWV7FXsNQXJE7UPIr9ccxA.unload = ((void*) (on_unload__zfoBJ1FmbMCz6PPaUkQHLw));
	nimTestErrorFlag();
	popFrame();
}
}

