/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include "erl_nif.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Option__B2fjAwynjxmQWpd3bed9cLw tyObject_Option__B2fjAwynjxmQWpd3bed9cLw;
typedef struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA;
typedef struct tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct tyObject_Option__B2fjAwynjxmQWpd3bed9cLw {
tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* val;
};
struct tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA {
ErlNifResourceType* val;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA {
NF kp;
NF ki;
NF kf;
NF p;
NF i;
NF f;
NF r;
NF di;
NF min;
NF max;
NIM_BOOL integrate;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA, priv_data__HETKDuskSRU9cq8OrzcliqA)(ErlNifEnv* env);
static N_INLINE(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA, some__nylgUSQDKOPWqKqiI2R39aQoptions)(ErlNifResourceType* val);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isSome__wrIeeeykfpyl7dy3FZM9asQoptions)(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA self);
static N_INLINE(ErlNifResourceType*, unsafeGet__EOfxSPch4b3pN9bRQYJneagoptions)(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA self);
static N_INLINE(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, some__1Me0L8vR1P7DIWo9c9cFp4NAoptions)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* val);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[86+1];
} TM__icwbaCa49cdMaGzA9axlvsyQ_2 = { 86 | NIM_STRLIT_FLAG, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim(11"
"8, 11) `not val.isNil` " };
static const NimStringV2 TM__icwbaCa49cdMaGzA9axlvsyQ_3 = {86, (NimStrPayload*)&TM__icwbaCa49cdMaGzA9axlvsyQ_2};
static const struct {
  NI cap; NIM_CHAR data[84+1];
} TM__icwbaCa49cdMaGzA9axlvsyQ_4 = { 84 | NIM_STRLIT_FLAG, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim(37"
"2, 10) `self.isSome` " };
static const NimStringV2 TM__icwbaCa49cdMaGzA9axlvsyQ_5 = {84, (NimStrPayload*)&TM__icwbaCa49cdMaGzA9axlvsyQ_4};
static const NimStringV2 TM__icwbaCa49cdMaGzA9axlvsyQ_6 = {86, (NimStrPayload*)&TM__icwbaCa49cdMaGzA9axlvsyQ_2};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
static N_INLINE(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA, some__nylgUSQDKOPWqKqiI2R39aQoptions)(ErlNifResourceType* val) {
	tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA result;
NIM_BOOL* nimErr_;
	nimfr_("some", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA));
	nimln_(118, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		if (!!(!((val == 0)))) goto LA3_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__icwbaCa49cdMaGzA9axlvsyQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	nimln_(119, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result.val = val;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA, priv_data__HETKDuskSRU9cq8OrzcliqA)(ErlNifEnv* env) {
	tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA result;
	ErlNifResourceType* priv;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("priv_data", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA));
	nimln_(5, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	T1_ = (void*)0;
	T1_ = enif_priv_data(env);
	priv = ((ErlNifResourceType*) (T1_));
	nimln_(6, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	{
		if (!!((priv == 0))) goto LA4_;
		nimln_(7, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
		result = some__nylgUSQDKOPWqKqiI2R39aQoptions(priv);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isSome__wrIeeeykfpyl7dy3FZM9asQoptions)(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA self) {
	NIM_BOOL result;
	nimfr_("isSome", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = (NIM_BOOL)0;
	nimln_(144, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	nimln_(153, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result = !((self.val == 0));
	popFrame();
	return result;
}
static N_INLINE(ErlNifResourceType*, unsafeGet__EOfxSPch4b3pN9bRQYJneagoptions)(tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA self) {
	ErlNifResourceType* result;
NIM_BOOL* nimErr_;
	nimfr_("unsafeGet", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	result = (ErlNifResourceType*)0;
	nimln_(367, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	nimln_(372, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__wrIeeeykfpyl7dy3FZM9asQoptions(self);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__icwbaCa49cdMaGzA9axlvsyQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	result = self.val;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, some__1Me0L8vR1P7DIWo9c9cFp4NAoptions)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* val) {
	tyObject_Option__B2fjAwynjxmQWpd3bed9cLw result;
NIM_BOOL* nimErr_;
	nimfr_("some", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw));
	nimln_(118, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	{
		if (!!(!((val == 0)))) goto LA3_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__icwbaCa49cdMaGzA9axlvsyQ_6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	nimln_(119, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/options.nim");
	result.val = val;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, new_resource__r9byBO1Ma6IFzl2uk8SWYUw)(ErlNifEnv* env) {
	tyObject_Option__B2fjAwynjxmQWpd3bed9cLw result;
	tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA privdata;
NIM_BOOL* nimErr_;
	nimfr_("new_resource", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw));
	nimln_(21, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	privdata = priv_data__HETKDuskSRU9cq8OrzcliqA(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(22, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	{
		NIM_BOOL T3_;
		tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* res;
		ErlNifResourceType* T6_;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__wrIeeeykfpyl7dy3FZM9asQoptions(privdata);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(23, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
		T6_ = (ErlNifResourceType*)0;
		T6_ = unsafeGet__EOfxSPch4b3pN9bRQYJneagoptions(privdata);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T7_ = (void*)0;
		T7_ = enif_alloc_resource(((void*) (T6_)), ((size_t) (((NI) 88))));
		res = ((tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA*) (T7_));
		nimln_(24, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
		result = some__1Me0L8vR1P7DIWo9c9cFp4NAoptions(res);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long long, release_resource__303jJuWZQeBLgwKlpOxU4Q)(ErlNifEnv* env, tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* V) {
	unsigned long long result;
	unsigned long long term;
	nimfr_("release_resource", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
{	result = (unsigned long long)0;
	nimln_(16, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	term = enif_make_resource(env, ((void*) (V)));
	nimln_(17, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	enif_release_resource(((void*) (V)));
	nimln_(18, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	result = term;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw, get_resource__Wr1CzN6z01R3q9bCccSJpiA)(ErlNifEnv* env, unsigned long long term) {
	tyObject_Option__B2fjAwynjxmQWpd3bed9cLw result;
	tyObject_Option__HN9crX3Zp7bKsLjyyTLujIA privdata;
	tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* res;
NIM_BOOL* nimErr_;
	nimfr_("get_resource", "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__B2fjAwynjxmQWpd3bed9cLw));
	nimln_(10, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	privdata = priv_data__HETKDuskSRU9cq8OrzcliqA(env);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	res = (tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA*)0;
	nimln_(12, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
	{
		NIM_BOOL T3_;
		ErlNifResourceType* T5_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome__wrIeeeykfpyl7dy3FZM9asQoptions(privdata);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T3_)) goto LA4_;
		T5_ = (ErlNifResourceType*)0;
		T5_ = unsafeGet__EOfxSPch4b3pN9bRQYJneagoptions(privdata);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T3_ = enif_get_resource(env, term, ((void*) (T5_)), ((void*) (&res)));
		LA4_: ;
		if (!T3_) goto LA6_;
		nimln_(13, "/home/elcritch/projects/pt/widgetlords_nifs/src/nimler-3.1/niml"
"er/resources.nim");
		result = some__1Me0L8vR1P7DIWo9c9cFp4NAoptions(res);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	LA6_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
