/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA;

/* section: NIM_merge_TYPES */
struct tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA {
NF kp;
NF ki;
NF kf;
NF p;
NF i;
NF f;
NF r;
NF di;
NF min;
NF max;
NIM_BOOL integrate;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NF, clamp__raGZkfxASKJtrXnsu9b3IfA)(NF x, NF a, NF b);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, init_controller__DrEjcoZ9bECTPpHDjBtiS3A)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* control, NF rate, NF min, NF max, NF kp, NF ki, NF kf) {
	nimfr_("init_controller", "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	nimln_(15, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).min = min;
	nimln_(16, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).max = max;
	nimln_(17, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).di = ((NF)(1.0000000000000000e+00) / (NF)(rate));
	nimln_(18, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).integrate = NIM_TRUE;
	nimln_(19, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).kp = kp;
	nimln_(20, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).ki = ki;
	nimln_(21, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).kf = kf;
	nimln_(22, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).p = 0.0;
	nimln_(23, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).i = 0.0;
	nimln_(24, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).f = 0.0;
	nimln_(25, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).r = 0.0;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NF, update__hSL5GnyD0z5SnNrHLd50jA)(tyObject_PIControl__PxgH1MS9ctZxM8ab9beQYQvA* control, NF sp, NF pv, NF f) {
	NF result;
	NF error;
	nimfr_("update", "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	result = (NF)0;
	nimln_(42, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	error = ((NF)(sp) - (NF)(pv));
	nimln_(43, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).p = ((NF)((*control).kp) * (NF)(error));
	nimln_(44, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	{
		if (!(*control).integrate) goto LA3_;
		nimln_(45, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
		(*control).i = ((NF)((*control).i) + (NF)(((NF)(((NF)(error) * (NF)((*control).ki))) * (NF)((*control).di))));
	}
	LA3_: ;
	nimln_(46, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).f = ((NF)((*control).kf) * (NF)(f));
	nimln_(47, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	(*control).r = clamp__raGZkfxASKJtrXnsu9b3IfA(((NF)(((NF)((*control).p) + (NF)((*control).i))) + (NF)((*control).f)), (*control).min, (*control).max);
	nimln_(48, "/home/elcritch/projects/pt/widgetlords_nifs/nimsrc/controller.n"
"im");
	result = (*control).r;
	popFrame();
	return result;
}
